/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import config.Koneksi;
import controller.KamarController;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;
import main.App;
import model.Kamar;
import model.Kategori;

import main.App;

/**
 *
 * @author LENOVO
 */
public class KamarView extends javax.swing.JInternalFrame {

    private final Kamar kamar;
    private Kategori kategori;
    private List<Kamar> listKamar;
    private final KamarController kamarController;
    private Koneksi koneksi;

    /**
     * Creates new form KamarView
     */
    public KamarView() {
        initComponents();

        koneksi = new Koneksi();
        kamar = new Kamar(koneksi.getConnection());
        kategori = new Kategori(koneksi.getConnection());

        kamarController = new KamarController(this);
        kamarController.enableForm(false);
        kamarController.loadKategori();
        refreshTable();
        initListener();

    }

    public Kamar getKamar() {
        return kamar;
    }

    public Kategori getKategori() {
        return kategori;
    }

    public List<Kamar> getListKamar() {
        return listKamar;
    }

    public KamarController getKamarController() {
        return kamarController;
    }

    public JComboBox<String> getComboKategori() {
        return comboKategori;
    }

    public JComboBox<String> getComboStatus() {
        return comboStatus;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JLabel getJudul() {
        return judul;
    }

    public JTable getTabelKamar() {
        return tabelKamar;
    }

    public JTextField getTextHarga() {
        return textHarga;
    }

    public JTextField getTextNama() {
        return textNama;
    }

    public JTextField getTextNo() {
        return textNo;
    }

    public JButton getTombolBaru() {
        return tombolBaru;
    }

    public JButton getTombolHapus() {
        return tombolHapus;
    }

    public JButton getTombolSimpan() {
        return tombolSimpan;
    }

    public JButton getTombolUbah() {
        return tombolUbah;
    }

    private void refreshTable() {
        try {
            Kamar km = new Kamar(koneksi.getConnection());
            listKamar = km.getAll();
            tabelKamar.setModel(new KamarTableModel(listKamar));
        } catch (SQLException ex) {
            Logger.getLogger(KamarView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Gagal memuat data kamar!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void initListener() {
        tabelKamar.getSelectionModel().addListSelectionListener((ListSelectionEvent lse) -> {
            kamarController.loadData(kamar, listKamar);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        form = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboKategori = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        textHarga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();
        tombolBaru = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        tombolHapus = new javax.swing.JButton();
        tombolUbah = new javax.swing.JButton();
        tombolSimpan = new javax.swing.JButton();
        tabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKamar = new javax.swing.JTable();

        setClosable(true);
        setTitle("Data Kamar");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new java.awt.BorderLayout(0, 30));

        judul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        judul.setText("DATA KAMAR");
        jPanel1.add(judul);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 20, 2));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        form.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Form", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jPanel2.setLayout(new java.awt.GridLayout(6, 2, 10, 20));

        jLabel1.setText("No Kamar");
        jPanel2.add(jLabel1);
        jPanel2.add(textNo);

        jLabel2.setText("Nama");
        jPanel2.add(jLabel2);
        jPanel2.add(textNama);

        jLabel3.setText("Kategori");
        jPanel2.add(jLabel3);

        jPanel2.add(comboKategori);

        jLabel4.setText("Harga");
        jPanel2.add(jLabel4);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setText("Rp.");
        jPanel5.add(jLabel6);

        textHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textHargaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textHargaKeyTyped(evt);
            }
        });
        jPanel5.add(textHarga);

        jPanel2.add(jPanel5);

        jLabel5.setText("Status");
        jPanel2.add(jLabel5);

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Status --", "Tersedia", "DiSewa" }));
        jPanel2.add(comboStatus);

        tombolBaru.setText("Baru");
        tombolBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolBaruActionPerformed(evt);
            }
        });
        jPanel2.add(tombolBaru);

        tombolHapus.setText("Hapus");
        tombolHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusActionPerformed(evt);
            }
        });
        jPanel6.add(tombolHapus);

        tombolUbah.setText("Ubah");
        tombolUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolUbahActionPerformed(evt);
            }
        });
        jPanel6.add(tombolUbah);

        tombolSimpan.setText("Simpan");
        tombolSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolSimpanActionPerformed(evt);
            }
        });
        jPanel6.add(tombolSimpan);

        jPanel2.add(jPanel6);

        form.add(jPanel2);

        jPanel3.add(form);

        tabelKamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelKamar);

        tabel.add(jScrollPane1);

        jPanel3.add(tabel);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        App.getMenuView().kamarView = null;
    }//GEN-LAST:event_formInternalFrameClosed

    private void tombolBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBaruActionPerformed
        // TODO add your handling code here:
        kamarController.clearForm();
        kamarController.enableForm(true);
        textNo.requestFocusInWindow();
    }//GEN-LAST:event_tombolBaruActionPerformed

    private void tombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSimpanActionPerformed
        // TODO add your handling code here:
        if (kamarController.validasiInputBaru()) {
            try {
                Kategori kat = new Kategori(koneksi.getConnection());
                kategori = kat.getByNama(comboKategori.getSelectedItem().toString());

                kamar.setNoKamar(textNo.getText().trim());
                kamar.setNama(textNama.getText().trim());
                kamar.setKategori(kategori);
                kamar.setHarga(Double.parseDouble(textHarga.getText().trim()));
                kamar.setStatus(comboStatus.getSelectedItem().toString());

                kamar.simpan();

                JOptionPane.showMessageDialog(this, "Data berhasil disimpan!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                refreshTable();
                kamarController.clearForm();
                kamarController.enableForm(false);
            } catch (SQLException ex) {
                Logger.getLogger(KamarView.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Format harga tidak valid!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_tombolSimpanActionPerformed

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusActionPerformed
        // TODO add your handling code here:
        if (kamarController.validasiInput()) {
            kamar.setNoKamar(textNo.getText().trim());
            int konfirmasi = JOptionPane.showConfirmDialog(this,
                    "Apakah anda yakin akan menghapus data ini?",
                    "Konfirmasi",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (konfirmasi == JOptionPane.YES_OPTION) {
                try {
                    kamar.hapus();
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus!",
                            "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    refreshTable();
                    kamarController.clearForm();
                    kamarController.enableForm(false);
                } catch (SQLException ex) {
                    Logger.getLogger(KamarView.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + ex.getMessage(),
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_tombolHapusActionPerformed

    private void tombolUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolUbahActionPerformed
        // TODO add your handling code here:
        if (kamarController.validasiInput()) {
            try {
                Kategori kat = new Kategori(koneksi.getConnection());
                kategori = kat.getByNama(comboKategori.getSelectedItem().toString());

                kamar.setNoKamar(textNo.getText().trim());
                kamar.setNama(textNama.getText().trim());
                kamar.setKategori(kategori);
                kamar.setHarga(Double.parseDouble(textHarga.getText().trim()));
                kamar.setStatus(comboStatus.getSelectedItem().toString());

                kamar.ubah();

                JOptionPane.showMessageDialog(this, "Data berhasil diubah!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                refreshTable();
                kamarController.clearForm();
                kamarController.enableForm(false);
            } catch (SQLException ex) {
                Logger.getLogger(KamarView.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Gagal mengubah data: " + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Format harga tidak valid!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_tombolUbahActionPerformed

    private void textHargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textHargaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHargaKeyPressed

    private void textHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textHargaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Hanya Boleh Angka!", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_textHargaKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboKategori;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JPanel form;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JPanel tabel;
    private javax.swing.JTable tabelKamar;
    private javax.swing.JTextField textHarga;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textNo;
    private javax.swing.JButton tombolBaru;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolSimpan;
    private javax.swing.JButton tombolUbah;
    // End of variables declaration//GEN-END:variables

    public class KamarTableModel extends AbstractTableModel {

        private List<Kamar> listKamar = new ArrayList<>();
        private final String[] HEADER = {"No Kamar", "Nama", "Kategori", "Harga", "Status"};

        public KamarTableModel(List<Kamar> listKamar) {
            if (listKamar != null) {
                this.listKamar = listKamar;
            }
        }

        @Override
        public int getRowCount() {
            return listKamar.size(); // Mengembalikan jumlah baris berdasarkan jumlah kamar
        }

        @Override
        public int getColumnCount() {
            return HEADER.length; // Mengembalikan jumlah kolom berdasarkan HEADER
        }

        @Override
        public String getColumnName(int columnIndex) {
            return HEADER[columnIndex]; // Mengembalikan nama kolom berdasarkan HEADER
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Kamar km = listKamar.get(rowIndex); // Mendapatkan objek Kamar berdasarkan rowIndex
            switch (columnIndex) {
                case 0:
                    return km.getNoKamar();  // Kolom No Kamar
                case 1:
                    return km.getNama();  // Kolom Nama
                case 2:
                    return km.getKategori() != null ? km.getKategori().getNama() : "Tidak Ada Kategori";  // Kolom Kategori
                case 3:
                    return km.getHarga();  // Kolom Harga
                case 4:
                    return km.getStatus();  // Kolom Status
                default:
                    return null; // Jika kolom tidak dikenali
            }
        }
    }

}
