/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import config.Koneksi;
import controller.KategoriController;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.AbstractTableModel;
import main.App;
import model.Kategori;

/**
 *
 * @author LENOVO
 */
public class KategoriView extends javax.swing.JInternalFrame {

    private final Kategori kategori;
    private List<Kategori> listKategori;
    private KategoriController kategoriController;
    private Koneksi koneksi;

    public KategoriView() {
        initComponents();
        koneksi = new Koneksi();
        kategori = new Kategori(koneksi.getConnection());

        kategoriController = new KategoriController(this);
        kategoriController.enableForm(false);
        refreshTable();
        initListener();
    }

    public JTextField getTextId() {
        return textId;
    }

    public JTextField getTextNama() {
        return textNama;
    }

    public JButton getTombolBaru() {
        return tombolBaru;
    }

    public JButton getTombolHapus() {
        return tombolHapus;
    }

    public JButton getTombolSimpan() {
        return tombolSimpan;
    }

    public JButton getTombolUbah() {
        return tombolUbah;
    }

    public JTable getTabelKategori() {
        return tabelKategori;
    }

    private void refreshTable() {
        try {
            Kategori k = new Kategori(koneksi.getConnection());
            listKategori = k.getAll();
            tabelKategori.setModel(new KategoriTableModel(listKategori));
        } catch (SQLException ex) {
            Logger.getLogger(KategoriView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Gagal memuat data kategori!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void initListener() {
        tabelKategori.getSelectionModel().addListSelectionListener((ListSelectionEvent lse) -> {
            kategoriController.loadData(kategori, listKategori);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        form = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        laabelKategori = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        labelNama = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        tombolBaru = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        tombolSimpan = new javax.swing.JButton();
        tombolHapus = new javax.swing.JButton();
        tombolUbah = new javax.swing.JButton();
        tabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKategori = new javax.swing.JTable();

        setClosable(true);
        setTitle("Data Kategori");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Thonburi", 1, 24)); // NOI18N
        jLabel1.setText("Data kategori");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        form.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Form", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jPanel2.setLayout(new java.awt.GridLayout(3, 2, 15, 15));

        laabelKategori.setText("ID Kategori :");
        jPanel2.add(laabelKategori);

        textId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdActionPerformed(evt);
            }
        });
        jPanel2.add(textId);

        labelNama.setText("Nama Kategori :");
        jPanel2.add(labelNama);
        jPanel2.add(textNama);

        tombolBaru.setText("Baru");
        tombolBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolBaruActionPerformed(evt);
            }
        });
        jPanel2.add(tombolBaru);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        tombolSimpan.setText("Simpan");
        tombolSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolSimpanActionPerformed(evt);
            }
        });
        jPanel3.add(tombolSimpan);

        tombolHapus.setText("Hapus");
        tombolHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusActionPerformed(evt);
            }
        });
        jPanel3.add(tombolHapus);

        tombolUbah.setText("Ubah");
        tombolUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolUbahActionPerformed(evt);
            }
        });
        jPanel3.add(tombolUbah);

        jPanel2.add(jPanel3);

        form.add(jPanel2);

        jPanel4.add(form);

        tabelKategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelKategori.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelKategoriAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tabelKategori);

        tabel.add(jScrollPane1);

        jPanel4.add(tabel);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        App.getMenuView().kategoriView = null;
    }//GEN-LAST:event_formInternalFrameClosed

    private void textIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIdActionPerformed

    private void tombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSimpanActionPerformed
        if (kategoriController.validasiInputBaru()) {
            try {
                kategori.setId(textId.getText());
                kategori.setNama(textNama.getText());
                kategori.simpan();
                
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                refreshTable();
            } catch (SQLException ex) {
                Logger.getLogger(KategoriView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tombolSimpanActionPerformed

    private void tombolBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBaruActionPerformed
        // TODO add your handling code here:
        kategoriController.clearForm();
        kategoriController.enableForm(true);
        textId.requestFocusInWindow();
    }//GEN-LAST:event_tombolBaruActionPerformed

    private void tombolUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolUbahActionPerformed
        // TODO add your handling code here:
        if (kategoriController.validasiInput()) {
            try {
                kategori.setId(textId.getText());
                kategori.setNama(textNama.getText());
                kategori.ubah();
                
                JOptionPane.showMessageDialog(this, "Data berhasil diubah !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                refreshTable();
            } catch (SQLException ex) {
                Logger.getLogger(KategoriView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tombolUbahActionPerformed

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusActionPerformed
        // TODO add your handling code here:

        if (kategoriController.validasiInput()) {
            kategori.setId(textId.getText());
            int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah anda yakin akan menghapus data ini?", "Konfirmasi", JOptionPane.WARNING_MESSAGE);
            if (konfirmasi == 0) {
                try {
                    kategori.hapus();
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    refreshTable();
                    kategoriController.clearForm();;
                } catch (SQLException ex) {
                    Logger.getLogger(KategoriView.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        }
    }//GEN-LAST:event_tombolHapusActionPerformed

    private void tabelKategoriAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelKategoriAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelKategoriAncestorAdded

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel form;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel laabelKategori;
    private javax.swing.JLabel labelNama;
    private javax.swing.JPanel tabel;
    private javax.swing.JTable tabelKategori;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textNama;
    private javax.swing.JButton tombolBaru;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolSimpan;
    private javax.swing.JButton tombolUbah;
    // End of variables declaration//GEN-END:variables

    public class KategoriTableModel extends AbstractTableModel {

        private List<Kategori> listKategori = new ArrayList<>();

        private final String HEADER[] = {"ID Kategori", "Nama Kategori"};

        public KategoriTableModel(List<Kategori> listKategori) {
            this.listKategori = listKategori;
        }

        @Override
        public int getRowCount() { // jumlah baris
            return listKategori.size();
        }

        @Override
        public int getColumnCount() { // jumlah kolom
            return HEADER.length;
        }

        @Override
        public String getColumnName(int i) { // nama kolom
            return HEADER[i];
        }

        @Override
        public Object getValueAt(int i, int i1) { // mengisi data
            Kategori k = listKategori.get(i); // baris
            switch (i1) { // kolom
                case 0:
                    return k.getId();
                case 1:
                    return k.getNama();
                default:
                    return null;
            }
        }
    }
}
